spring.application.name=tailor-master-app
server.servlet.context-path=/tailor-master
#server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/tailor_master
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update


#spring.datasource.url=jdbc:mysql://tailor-dev-db.c1au0osqouie.ap-southeast-1.rds.amazonaws.com:3306/dev_tailor_master_db?useSSL=false&allowPublicKeyRetrieval=true
#spring.datasource.username=dev_tailor_user
#spring.datasource.password=Dev_Tailor@123
#spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true

# Optional but recommended
#spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
#spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect