spring.application.name=tailor-master-app
server.servlet.context-path=/tailor-master
#server.address=0.0.0.0

spring.datasource.url=jdbc:mysql://localhost:3306/tailor_master
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update

google.drive.client-secret-file=C:/TailorMaster/credentials/client_secret.json
google.drive.application-name=tailor_master_local_test
google.drive.tokens-directory=C:/TailorMaster/credentials/token-store

spring.messages.basename=messages
spring.messages.encoding=UTF-8